services:
  # Backend Service
  - name: socketproject-backend
    type: web
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: GEMINI_API_KEY
        value: AIzaSyDzZ1Vp7sokOh89Qt0Vm8j57-RSubfAMno
      - key: NODE_ENV
        value: production
    plan: free
    autoDeploy: true
    rootDir: server # Path to the backend folder

