services:
  - name: socketproject-backend
    type: web
    env: node
    buildCommand: npm install
    startCommand: npm start
    envVars:
      - key: GEMINI_API_KEY
        value: <your-google-genai-api-key> # Replace with your actual API key
    plan: free
    autoDeploy: true
    region: oregon
    rootDir: server # Path to the backend folder

  - name: socketproject-frontend
    type: static
    buildCommand: npm install && npm run build
    publishPath: client/build # Path to the frontend build folder
    plan: free
    autoDeploy: true
    region: oregon
